---
title: 'STAT350: Final Project'
author: "David Huu Pham / dhpham@sfu.ca / 301318482"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir=rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo=T, warning=F, error=F, message=F)

rm(list = ls(all.names = T))
library(tidyverse)
```

```{r read-data}
death.csv.raw <- read_csv("data/proj/death.csv")
incd.csv.raw <- read_csv("data/proj/incd.csv")

head(death.csv.raw)
head(incd.csv.raw)
```

```{r tidy-data}
tidy_and_asnumeric <- function(.data, .cols.asnumeric) {
  tidy_colnames <- .data %>%
    # Removes footnote numbers from column names and County names
    rename_with(~ str_remove(.x, "\\?? ?\\(.*\\)")) %>%
    mutate(County = str_remove_all(County, " ?\\(.*\\)")) %>%
    mutate(County = str_remove_all(County, " ?<.*>")) %>%
    # Creates a column for State, removes State from County
    separate(col=County, into=c("County", "State"), sep=", ")

  # Alter the rows for US and District of Columbia to match across csv files
  tidy_us.dc <- tidy_colnames %>%
    filter(FIPS == 0 | )

    # Convert State to factors
    mutate(State = as_factor(State)) %>%
    
    # Remove any non-numeric characters from the columns we want to convert to numeric
    mutate(across(
      .cols = starts_with(.cols.asnumeric), 
      .fns = ~ str_remove_all(.x, "[^\\+\\-\\.[:digit:]]+")
    )) %>%
    # Convert columns to numeric
    mutate(across(
      .cols = starts_with(.cols.asnumeric), 
      .fns = as.numeric
    )) %>%
    # Filter out any rows with missing rates data
    filter_at(
      vars(starts_with(.cols.asnumeric)), 
      any_vars(!is.na(.))
    )
  
}

# Convert these columns to numeric data types
incd.cols.asnumeric <- c("Age-Adjusted", "Upper", "Lower", "Average", "Recent 5")
# Split data up based on rate and trends
incd.untidy.rates <- incd.csv.raw %>% select(1:5)
incd.untidy.trends <- incd.csv.raw %>% select(1:2, !(3:5))

incd.tidy.rates <- tidy_and_asnumeric(incd.untidy.rates, incd.cols.asnumeric)
incd.tidy.trends <- tidy_and_asnumeric(incd.untidy.trends, incd.cols.asnumeric) %>%
  rename("Average Incidence Counts per Year" = "Average Annual Count",
         "Lower 95% Confidence Interval for Trend in Incidence Rate" = "Lower 95% Confidence Interval_1", 
         "Upper 95% Confidence Interval for Trend in Incidence Rate" = "Upper 95% Confidence Interval_1")


# Convert these columns to numeric data types
death.cols.asnumeric <- c("Upper", "Lower", "Recent 5")
# Convert these columns to logical data types
death.cols.aslogical <- c("Met Objective")
death.csv.aslogical <- death.csv.raw %>%
  mutate(across(
    .cols = starts_with(death.cols.aslogical),
    .fns = str_detect,
    pattern = fixed("yes", ignore_case=TRUE)
  ))

death.untidy.rates <- death.csv.aslogical %>% select(1:6)
death.untidy.trends <- death.csv.aslogical %>% select(1:3, 7:last_col())

death.tidy.rates <- tidy_and_asnumeric(death.untidy.rates, death.cols.asnumeric)
death.tidy.trends <- tidy_and_asnumeric(death.untidy.trends, death.cols.asnumeric) %>%
  rename_with(~ str_replace(.x, "Interval for Trend$", "Interval for Trend in Death Rates"))
```

```{r data-visualizations-bystate, fig.height=6}

incd.rates.bystate <- incd.tidy.rates %>%
  group_by(State) %>%
  summarize(
    n.incd = n(),
    mean.incidence.rate = mean(`Age-Adjusted Incidence Rate - cases per 100,000`)
  )

death.rates.bystate <- death.tidy.rates %>%
  group_by(State) %>%
  summarize(
    n.death = n(),
    mean.death.rate = mean(`Age-Adjusted Death Rate`)
  )

rates.bystate <- incd.rates.bystate %>%
  inner_join(death.rates.bystate, by="State")

rates.bystate %>%
  summarize(total.mean = mean(mean.incidence.rate))

ggplot(rates.bystate, aes(x=mean.incidence.rate, y=fct_reorder(State, mean.incidence.rate))) +
  geom_col(aes(fill = n.incd)) +
  labs(x = "Mean of the Age-Adjusted Incidence Rate, Cases per 100K", y = "State")

ggplot(rates.bystate, aes(x=mean.death.rate, y=fct_reorder(State, mean.incidence.rate))) +
  geom_col(aes(fill = n.death))

ggplot(rates.bystate, aes(x=mean.death.rate, y=mean.incidence.rate)) +
  geom_point()
```


```{r data-visualizations-bycounty, fig.height=6}

rates.bycounty <- incd.tidy.rates %>%
  inner_join(death.tidy.rates, by=c("FIPS"="FIPS", "State"="State"))
rates.bycounty %>%
  filter(County.x != County.y)

ggplot(rates.bystate, aes(x=mean.incidence.rate, y=fct_reorder(State, mean.incidence.rate))) +
  geom_col(aes(fill = n.incd)) +
  labs(x = "Mean of the Age-Adjusted Incidence Rate, Cases per 100K", y = "State")

ggplot(rates.bystate, aes(x=mean.death.rate, y=fct_reorder(State, mean.incidence.rate))) +
  geom_col(aes(fill = n.death))

ggplot(rates.bystate, aes(x=mean.death.rate, y=mean.incidence.rate)) +
  geom_point()
```